[package]
name = "mpz-zk"
version = "0.1.0-alpha.3"
edition = "2024"

[lints]
workspace = true

[features]
default = ["rayon"]
rayon = ["mpz-zk-core/rayon", "mpz-common/rayon"]

[dependencies]
async-trait = { workspace = true }
blake3 = { workspace = true, features = ["serde"] }
futures = { workspace = true }
serio = { workspace = true }
thiserror = { workspace = true }
mpz-common = { workspace = true }
mpz-core = { workspace = true }
mpz-ot = { workspace = true }
mpz-vm-core = { workspace = true }
mpz-zk-core = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
mpz-circuits = { workspace = true }
mpz-common = { workspace = true, features = [
    "test-utils",
    "ideal",
    "executor",
] }
mpz-ot = { workspace = true, features = ["ideal"] }
rand = { workspace = true }
tokio = { workspace = true, features = [
    "net",
    "macros",
    "rt",
    "rt-multi-thread",
] }

[[bench]]
name = "zk"
harness = false
