[package]
name = "mpz-zk"
version = "0.1.0-alpha.4"
edition = "2024"

[lints]
workspace = true

[features]
default = []
rayon = ["mpz-zk-core/rayon", "blake3/rayon"]

[dependencies]
mpz-vm-core = { workspace = true }
mpz-zk-core = { workspace = true }
mpz-ot = { workspace = true }
mpz-core = { workspace = true }
mpz-common = { workspace = true }

async-trait = { workspace = true }
blake3 = { workspace = true, features = ["serde"] }
derive_builder = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
serio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = [
    "net",
    "macros",
    "rt",
    "rt-multi-thread",
    "io-util",
] }
tokio-util = { workspace = true, features = ["compat"] }
rand = { workspace = true }
mpz-circuits = { workspace = true, features = ["aes"] }
mpz-common = { workspace = true, features = [
    "test-utils",
    "ideal",
    "executor",
] }
mpz-ot = { workspace = true, features = ["ideal"] }
criterion = { workspace = true }

[[bench]]
name = "zk"
harness = false
required-features = ["rayon"]

[[bench]]
name = "batch_size"
harness = false
required-features = ["rayon"]

[[bench]]
name = "prover"
harness = false
required-features = ["rayon"]

[[bench]]
name = "verifier"
harness = false
required-features = ["rayon"]

[[bench]]
name = "recording_overhead"
harness = false
required-features = ["rayon"]
