    Finished `release` profile [optimized] target(s) in 0.05s
     Running `target/release/estimator regular 128 1000`

This program searches primal LPN instances over F2 satisfying a minimum bit security for a given secret length.
Output is formatted rust code written to STDOUT, which can be included as a module in other projects.

Parameters: type, s, t, max_n (optional)
	type - either "exact" or "regular"
	s - minimum bit security
	t - hamming weight of the error
	max_n (optional) - maximum number of samples to search for

//! Do NOT edit this file manually!
//!
//! This module is automatically generated with the crate `lpn-estimator` using
//! the binary `estimator.rs`. If you want to make changes run the estimator and
//! replace this file with the generated output.
use mpz_core::lpn::LpnParameters;
/// LPN parameters.
pub static LPN_PARAMS: &[LpnParameters] = &[
    LpnParameters {
        n: 256000usize,
        k: 18639usize,
        t: 1000usize,
    },
    LpnParameters {
        n: 512000usize,
        k: 35137usize,
        t: 1000usize,
    },
    LpnParameters {
        n: 1024000usize,
        k: 66247usize,
        t: 1000usize,
    },
    LpnParameters {
        n: 2048000usize,
        k: 124910usize,
        t: 1000usize,
    },
    LpnParameters {
        n: 4096000usize,
        k: 247302usize,
        t: 1000usize,
    },
    LpnParameters {
        n: 8192000usize,
        k: 466318usize,
        t: 1000usize,
    },
    LpnParameters {
        n: 16384000usize,
        k: 879301usize,
        t: 1000usize,
    },
    LpnParameters {
        n: 32768000usize,
        k: 1740949usize,
        t: 1000usize,
    },
];
