//! Do NOT edit this file manually!
//!
//! This module is automatically generated with the crate `lpn-estimator` using
//! the binary `estimator.rs`. If you want to make changes run the estimator and
//! replace this file with the generated output.
use mpz_core::lpn::LpnParameters;
/// LPN parameters.
pub static LPN_PARAMS: &[LpnParameters] = &[
    LpnParameters {
        n: 256000usize,
        k: 13249usize,
        t: 2000usize,
    },
    LpnParameters {
        n: 512000usize,
        k: 22653usize,
        t: 2000usize,
    },
    LpnParameters {
        n: 1024000usize,
        k: 38737usize,
        t: 2000usize,
    },
    LpnParameters {
        n: 2048000usize,
        k: 69559usize,
        t: 2000usize,
    },
    LpnParameters {
        n: 4096000usize,
        k: 131155usize,
        t: 2000usize,
    },
    LpnParameters {
        n: 8192000usize,
        k: 247302usize,
        t: 2000usize,
    },
    LpnParameters {
        n: 16384000usize,
        k: 466318usize,
        t: 2000usize,
    },
    LpnParameters {
        n: 32768000usize,
        k: 879301usize,
        t: 2000usize,
    },
];
