//! Generates test fixture data for GPU sum_slots correctness testing.
//!
//! Run with: cargo run -p bgv-webgpu --example generate_fixture > crates/bgv-webgpu/src/fixture.rs
//!
//! This generates deterministic Galois keys from a fixed seed that can be used
//! for both correctness tests and benchmarks.

use mpz_justvengers_core::{
    RnsKeyPair, RnsCiphertext, RnsGaloisKeys, RnsBgvParams,
};
use mpz_core::prg::Prg;

fn main() {
    eprintln!("Generating fixture data for Goldilocks parameters...");
    eprintln!("This will take a while due to key generation...");

    // Use fixed seed for deterministic generation
    let mut rng = Prg::new_with_seed([0u8; 16]);

    // Use production Goldilocks parameters (3 moduli)
    let params = RnsBgvParams::goldilocks();
    let n = params.n;
    let num_moduli = params.num_moduli;

    eprintln!("Parameters: n={}, num_moduli={}", n, num_moduli);

    // Generate keypair
    eprintln!("Generating keypair...");
    let keypair = RnsKeyPair::generate(&params, &mut rng);

    // Generate Galois keys for sum_slots (13 keys for n=8192)
    eprintln!("Generating Galois keys (this is slow)...");
    let galois_keys = RnsGaloisKeys::generate(&keypair.sk, &mut rng);

    // Create a test ciphertext with known slot values
    eprintln!("Creating test ciphertext...");
    let test_slots: Vec<u64> = (0..n).map(|i| (i as u64) % 1000).collect();
    let test_ct = RnsCiphertext::encrypt_slots(&keypair.pk, &test_slots, &mut rng);

    // Compute expected sum
    let t = params.t;
    let expected_sum: u64 = test_slots.iter().fold(0u128, |acc, &x| (acc + x as u128) % t as u128) as u64;

    eprintln!("Expected sum of slots: {}", expected_sum);

    // Now output the Rust fixture code
    println!("//! Auto-generated test fixture for GPU sum_slots.");
    println!("//!");
    println!("//! Generated by: cargo run -p bgv-webgpu --example generate_fixture");
    println!("//! DO NOT EDIT MANUALLY.");
    println!();
    println!("/// Expected sum of test slots (0..8192 mod 1000).");
    println!("pub const EXPECTED_SUM: u64 = {};", expected_sum);
    println!();
    println!("/// Number of Galois keys (log2(n) for sum_slots).");
    println!("pub const NUM_GALOIS_KEYS: usize = {};", galois_keys.num_keys());
    println!();

    // Output Galois key data
    // Each key has: k (exponent), keys_b, keys_a
    // keys_b and keys_a are Vec<RnsPoly> with num_limbs * digits_per_limb entries
    // Each RnsPoly has num_moduli residue vectors of length n

    println!("/// Galois key automorphism exponents.");
    print!("pub const GALOIS_KEY_EXPONENTS: [usize; {}] = [", galois_keys.num_keys());
    for (i, k) in galois_keys.automorphism_exponents().iter().enumerate() {
        if i > 0 { print!(", "); }
        print!("{}", k);
    }
    println!("];");
    println!();

    // For each Galois key, output the key data
    for (key_idx, gk) in galois_keys.keys().iter().enumerate() {
        eprintln!("Outputting Galois key {} of {}...", key_idx + 1, galois_keys.num_keys());

        let k = gk.k();
        let keys_b = gk.keys_b();
        let keys_a = gk.keys_a();

        println!("/// Galois key {} (k={}): keys_b data.", key_idx, k);
        println!("/// Shape: [num_limbs * digits_per_limb][num_moduli][n]");
        print!("pub const GALOIS_KEY_{}_B: &[&[&[u64]]] = &[", key_idx);

        for (poly_idx, poly) in keys_b.iter().enumerate() {
            if poly_idx > 0 { print!(", "); }
            print!("&[");
            for (mod_idx, residue) in poly.residues().iter().enumerate() {
                if mod_idx > 0 { print!(", "); }
                print!("&[");
                for (coeff_idx, &coeff) in residue.iter().enumerate() {
                    if coeff_idx > 0 { print!(", "); }
                    print!("{}", coeff);
                }
                print!("]");
            }
            print!("]");
        }
        println!("];");

        println!("/// Galois key {} (k={}): keys_a data.", key_idx, k);
        print!("pub const GALOIS_KEY_{}_A: &[&[&[u64]]] = &[", key_idx);

        for (poly_idx, poly) in keys_a.iter().enumerate() {
            if poly_idx > 0 { print!(", "); }
            print!("&[");
            for (mod_idx, residue) in poly.residues().iter().enumerate() {
                if mod_idx > 0 { print!(", "); }
                print!("&[");
                for (coeff_idx, &coeff) in residue.iter().enumerate() {
                    if coeff_idx > 0 { print!(", "); }
                    print!("{}", coeff);
                }
                print!("]");
            }
            print!("]");
        }
        println!("];");
        println!();
    }

    // Output test ciphertext
    eprintln!("Outputting test ciphertext...");
    println!("/// Test ciphertext c0 residues.");
    print!("pub const TEST_CT_C0: &[&[u64]] = &[");
    for (mod_idx, residue) in test_ct.c0().residues().iter().enumerate() {
        if mod_idx > 0 { print!(", "); }
        print!("&[");
        for (coeff_idx, &coeff) in residue.iter().enumerate() {
            if coeff_idx > 0 { print!(", "); }
            print!("{}", coeff);
        }
        print!("]");
    }
    println!("];");

    println!("/// Test ciphertext c1 residues.");
    print!("pub const TEST_CT_C1: &[&[u64]] = &[");
    for (mod_idx, residue) in test_ct.c1().residues().iter().enumerate() {
        if mod_idx > 0 { print!(", "); }
        print!("&[");
        for (coeff_idx, &coeff) in residue.iter().enumerate() {
            if coeff_idx > 0 { print!(", "); }
            print!("{}", coeff);
        }
        print!("]");
    }
    println!("];");

    // Output secret key for decryption verification
    println!();
    println!("/// Secret key polynomial residues (for decryption verification).");
    print!("pub const SECRET_KEY: &[&[u64]] = &[");
    for (mod_idx, residue) in keypair.sk.s().residues().iter().enumerate() {
        if mod_idx > 0 { print!(", "); }
        print!("&[");
        for (coeff_idx, &coeff) in residue.iter().enumerate() {
            if coeff_idx > 0 { print!(", "); }
            print!("{}", coeff);
        }
        print!("]");
    }
    println!("];");

    eprintln!("Done! Fixture generation complete.");
}
